---
- name: Ensure DNS Points to Management DNS
  ansible.windows.win_dns_client:
    adapter_names: '*'
    dns_servers: "{{ mgmt_dns }}"
  when: mgmt_dns is defined and mgmt_dns | length > 0

- name: Join the host to the domain
  microsoft.ad.membership:
    dns_domain_name: "{{ domain }}"
    domain_admin_user: "{{ greyteam_user }}@{{ domain }}"
    domain_admin_password: "{{ greyteam_password }}"
    hostname: "{{ inventory_hostname_short }}"
    state: domain
    reboot: true

- name: Wait for host to reboot and reconnect
  ansible.windows.win_reboot:
    reboot_timeout: 1800

- name: Ensure the secure channel is established
  ansible.windows.win_shell: nltest /sc_verify:{{ domain }}
  register: trust_check
  retries: 5
  delay: 15
  until: trust_check.rc == 0

- name: Create Domain Account Profiles
  ansible.windows.win_user_profile:
    username: "{{ domain }}\\{{ item }}"
    state: present
  loop: "{{ domain_users + domain_admins }}"