---
- name: Check if computer is joined and if trust is valid
  ansible.windows.win_shell: |
    try {
        if (Test-ComputerSecureChannel) { return "VALID" } else { return "BROKEN" }
    } catch {
        return "BROKEN"
    }
  register: trust_check
  changed_when: false

- name: Force Unjoin from Domain if Trust is Broken
  microsoft.ad.membership:
    membership_state: workgroup
    workgroup_name: WORKGROUP
    local_admin_user: "{{ greyteam_user }}"
    local_admin_password: "{{ greyteam_password }}"
    reboot: true
  when: trust_check.stdout | trim == "BROKEN"