- name: Ensure branding directory exists
  ansible.windows.win_file:
    path: C:\ProgramData\Inscope\Branding
    state: directory

- name: Copy wallpaper to branding directory
  ansible.windows.win_copy:
    src: evilwallpaper.jpg
    dest: C:\ProgramData\Inscope\Branding\wallpaper.jpg