###########################
### Windows Teams Setup ###
###########################
# These roles deploy essential team infra used in every
# competition (like DC servers and general box configuration)

- name: Run Windows Standards 
  hosts: windows:&team_hosts
  roles:
    - windows_deploy_standards
  tags: 
    - windows
    - team
    - standards
    - stds

- name: Create Local Users
  hosts: windows:&team_hosts
  roles:
    - windows_deploy_local_users
  tags:
  - windows
  - team
  - local_users

- name: Install Utilities
  hosts: windows:&team_hosts
  roles:
    - windows_deploy_utilities
  tags:
    - windows
    - team
    - utilities

- name: Set Wallpaper
  hosts: windows:&team_hosts
  roles:
    - windows_deploy_wallpaper
  tags:
    - windows
    - team
    - wallpaper

###########################
# Windows Scored Services #
###########################
# These roles deploy nonessential infrastructure, such
# as scored or unscored services and other scoring items.

- name: Deploy IIS 
  hosts: windows:&team_hosts
  roles: 
    - windows_deploy_iis
  tags: 
    - windows
    - team
    - iis

- name: Deploy SMB Share 
  hosts: windows:&team_hosts
  roles:
    - windows_deploy_smb
  tags:
    - windows
    - team
    - smb

###########################
###### Windows Misc #######
###########################
# These roles are only ran to fix issues or to do end of execution cleanup.

- name: Post Deploy Cleanup
  hosts: windows:&team_hosts
  roles:
    - windows_post_deploy
  tags:
    - windows 
    - team 
    - cleanup 
    - post_deploy_cleanup
    - post_deploy
    - wrap_it_up