---
- name: Linux | Ensure Local Backup Directory Exists
  ansible.builtin.file:
    path: "{{ local_backup_root }}"
    state: directory
    mode: '0700'

- name: Linux | Copy to Local Backup Folder
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ local_backup_root }}/{{ item | basename }}"
    remote_src: yes
    mode: preserve
  loop: "{{ magpie_protected_folders }}"
  ignore_errors: yes

- name: Linux | Fetch to Controller
  ansible.builtin.fetch:
    src: "{{ item }}"
    dest: "{{ controller_backup_root }}/{{ inventory_hostname_short }}/"
    flat: no
  loop: "{{ magpie_protected_folders }}"