---
- name: Backup Scored Services
  hosts: inscope
  roles:
    - backup
  tags:
    - backup
    - full

- name: Apply Firewall Script
  hosts: inscope
  roles:
    - firewall
  tags:
    - firewall
    - full

- name: Deploy Birdsnest
  hosts: all
  roles:
    - birdsnest
  tags:
    - birdsnest
    - full

- name: Deploy Magpie
  hosts: inscope
  roles:
    - birdsnest-magpie
  tags:
    - magpie
    - full

- name: Deploy Owlet
  hosts: inscope
  roles:
    - birdsnest-owlet
  tags:
    - owlet
    - full

- name: Deploy Kingfisher
  hosts: inscope
  roles:
    - birdsnest-kingfisher
  tags:
    - kingfisher
    - full