---
- name: Windows AD | Perform Users Inscope Tasks
  ansible.builtin.include_tasks: windows.yaml
  when: "'10.2.1.3' in ansible_all_ipv4_addresses"

- name: Windows | Perform Users Inscope Tasks
  ansible.builtin.include_tasks: windows.yaml
  when: ansible_os_family == "Windows"
    
- name: Linux | Perform Users Inscope Tasks
  ansible.builtin.include_tasks: linux.yaml
  when: ansible_os_family != "Windows"