---
blueteam_users:
- one
- two
- three
blueteam_password: blueteam

ansible_user: blueteam
ansible_password: blueteam
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
birdsnest_token: testtoken
birdsnest_host: 10.20.1.21:443
birdsnest_host_ip: 10.20.1.21
controller_backup_root: /backups

legit_ips:
  - 10.20.1.73 # team 2 jump 1
  - 10.20.1.132 
  - 10.20.1.71
  - 10.20.1.111
  - 10.20.1.57
  - 10.20.1.20
  - 10.20.1.46
  - 10.20.1.37
  - 10.20.1.16
  - 10.20.1.29 # team 2 jump 10
  #- 100.65.4.233 # scoring - what is internal?

out_of_scope_users:
  - greyteam
  - grayteam
  - cyberrange

legit_local_admins:
  - king
  - duke
  - knight
  - lady
  - baron
legit_local_users:
  - scribe
  - apothecary
  - shepherd
  - blacksmith
  - herald
legit_domain_users:
  - chancellor
  - wizard
  - treasurer
  - spymaster
  - archbishop
legit_domain_admins:
  - steward
  - stablemaster
  - royalguard
  - inquisitor
  - jester