---
redteam_user: redteam
redteam_password: evilpuck4me$you!
greyteam_user: greyteam
greyteam_password: ponyuploc0!
team_password: Change.me123!

#ansible_user: redteam
#ansible_password: "abcdefg"
#ansible_user: redteam
#ansible_password: "{{ team_password }}"
ansible_user: "{{ redteam_user }}"
ansible_password: "{{ redteam_password }}"
#ansible_user: "{{ greyteam_user }}"
#ansible_password: "{{ greyteam_password }}"
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

domain: redteam.local
dns_overrides: [] # remove [] if using an actual value below
  #- { ip: '192.168',    name: 'redteam.local' }
  #- { ip: '10.0.10.1',    name: 'canterlot.mlp.local' }
  #- { ip: '10.0.10.1',    name: 'dc.mlp.local' }
  #- { ip: '172.20.0.100', name: 'scoring.mlp.local' }

birdsnest_token: testtoken
birdsnest_host: 192.168.10.11:443
birdsnest_host_ip: 192.168.10.11
controller_backup_root: /backups

legit_ips:
  - 10.20.1.73 # team 2 jump 1
  - 10.20.1.132 
  - 10.20.1.71
  - 10.20.1.111
  - 10.20.1.57
  - 10.20.1.20
  - 10.20.1.46
  - 10.20.1.37
  - 10.20.1.16
  - 10.20.1.29 # team 2 jump 10
  - 10.20.1.21 # testing
  #- 100.65.4.233 # scoring - what is internal?

out_of_scope_users:
  - greyteam
  - grayteam
  - cyberrange

legit_local_admins:
  - king
  - duke
  - knight
  - lady
  - baron
legit_local_users:
  - scribe
  - apothecary
  - shepherd
  - blacksmith
  - herald
legit_domain_users:
  - chancellor
  - wizard
  - treasurer
  - spymaster
  - archbishop
legit_domain_admins:
  - steward
  - stablemaster
  - royalguard
  - inquisitor
  - jester
legit_local_all: "{{ legit_local_admins + legit_local_users }}"
legit_domain_all: "{{ legit_domain_admins + legit_domain_users }}"



pwnhost: ""
#ansible_become: yes
#ansible_become_method: sudo
#ansible_become_pass: ccdc

flag: "andrew niebur"
wazuh_manager_ip: "100.64.10.150"
red_users:
#  - "redteam"
#  - "letredin"
#  - "warchief"
#  - "nowplayingintheaters"
#  - "identityfraud"
#  - "andrewniebur"
  - "bart"
#  - "higgins"
red_users_password: "Thedawginmebottomtext1!"
wazuh_installer_win_path: "C:\\Windows\\Temp\\dubinstaller.msi"
###################
# Secure
###################
secure_ansible_dir: "/ansible/red-teaming"
secure_redteam_pwd: "" # Doesn't really matter as pwd auth is disabled but still change it after downloading
secure_key_location: "/opt/inventory/id_ed25519.pub"
###################
# Siphon
###################
siphon_file_old_path: "/bin/bash"
siphon_file_new_path: "/bin/ash"
siphon_path: "/bin/siphon0"
siphon_logfile_path: "~/output_$TIMESTAMP" #TIMESTAMP is current system time in Y-M-D_H-M-S
siphon_server_ip: "{{ hostvars['siphoner_server']['ansible_host'] }}"
siphon_server_port: "920"

###################
# Doubletap
###################
doubletap_fuse_date: "2025-12-31"  # In format YYYY-MM-DD in America/New_York timezone
doubletap_fuse_time: "13:37:00"    # In format HH:MM:SS, using 24h time in America/New_York timezone
doubletap_fuse_armed: "true"      # true or false. Do not set to true unless you want to actually detonate for real!
doubletap_users: "blueteam ccdc" # Separated by spaces. Include the scored user and multiple other users for camo. Leave out at least 1 admin
doubletap_users_pwd: "R@nsomNot3"  # Password to set on the locked users
# ps1 loop
doubletap_ps1_loop_script_dest: "C:\\Program Files\\Windows Photo Viewer\\en-US\\Photo Index Manager.ps1"
doubletap_ps1_loop_run_key_name: "PhotoIndexManager"
doubletap_ps1_loop_log_path: "C:\\Program Files\\Windows Photo Viewer\\en-US\\Photo Index Manager Log.txt"
#doubletap_ps1_loop_log_path: $null
# ps1 service
doubletap_ps1_service_script_dest: "C:\\Windows\\apppatch\\ChromeReadinessCheck.ps1"
doubletap_ps1_service_service_name: "ChromeReadinessCheck"
doubletap_ps1_service_service_display_name: "Chrome Update Service Manager"
doubletap_ps1_service_log_path: "C:\\Windows\\apppach\\ChromeReadinessCheck_log.txt"
#doubletap_ps1_service_log_path: $null
# ps1 task
doubletap_ps1_task_script_dest: "C:\\Windows\\PolicyDefinitions\\policydefs_update"
doubletap_ps1_task_task_name: "Update Core Policy Definitions"
doubletap_ps1_task_log_path: "C:\\Windows\\PolicyDefinitions\\policydefs_update_log.txt"
#doubletap_ps1_task_log_path: $null
# sh cron
doubletap_sh_cron_script_path: "/etc/iproute2/rt_update"
doubletap_sh_cron_job_name: "iproute_rt_update"
doubletap_sh_cron_job_user: "root"
doubletap_sh_cron_log_path: "/etc/iproute2/rt_update_log"
#doubletap_sh_cron_log_path: "/dev/null"
# sh loop
doubletap_sh_loop_script_path: "/dev/devicelistener"
doubletap_sh_loop_service_name: "devlistener"
doubletap_sh_loop_log_path: "/etc/devicelistener_log"
#doubletap_sh_loop_log_path: "/dev/null"
# sh service
doubletap_sh_service_script_path: "/bin/gumper"
doubletap_sh_service_service_name: "gumper"
doubletap_sh_service_service_description: "Periodically runs gumper"
doubletap_sh_service_log_path: "/etc/gumper_log"
#doubletap_sh_service_log_path: "/dev/null"

###################
# Kiki
###################
#All
kiki_server_fqdn: "server.local"
kiki_authorize_token: "abcdefghijklmnopqrstuvwxyz1234567890"
#Client
software1_timestamp_file: "C:\\Path\\To\\software1_timestamp.txt"
software2_timestamp_file: "C:\\Path\\To\\software2_timestamp.txt"
software3_timestamp_file: "C:\\Path\\To\\software3_timestamp.txt"
kiki_restart_time_seconds: 60
kiki_service_name: "WinSvcUpdate"
kiki_service_display_name: "Windows Service Update"
kiki_agent_path: "C:\\ProgramData\\WinUpdate\\agent.ps1"
kiki_reinstall_age_minutes: 5  # If timestamp older than this, reinstall
kiki_log_to_con: "true"
kiki_log_to_file: "true"
kiki_log_to_file_path: "C:\agent_debug.log"
kiki_dry_run: "false"